/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JudgeDemoRouteImport } from './routes/judge-demo'
import { Route as NewRouteImport } from './routes/new'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AnalysesAnalysisIdRouteImport } from './routes/analyses.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeDemoRoute = JudgeDemoRouteImport.update({
  id: '/judge-demo',
  path: '/judge-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesAnalysisIdRoute = AnalysesAnalysisIdRouteImport.update({
  id: '/analyses/$analysisId',
  path: '/analyses/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/judge-demo': typeof JudgeDemoRoute
  '/new': typeof NewRoute
  '/tasks': typeof TasksRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/judge-demo': typeof JudgeDemoRoute
  '/new': typeof NewRoute
  '/tasks': typeof TasksRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/judge-demo': typeof JudgeDemoRoute
  '/new': typeof NewRoute
  '/tasks': typeof TasksRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/judge-demo'
    | '/new'
    | '/tasks'
    | '/analyses/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/judge-demo'
    | '/new'
    | '/tasks'
    | '/analyses/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/judge-demo'
    | '/new'
    | '/tasks'
    | '/analyses/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JudgeDemoRoute: typeof JudgeDemoRoute
  NewRoute: typeof NewRoute
  TasksRoute: typeof TasksRoute
  AnalysesAnalysisIdRoute: typeof AnalysesAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-demo': {
      id: '/judge-demo'
      path: '/judge-demo'
      fullPath: '/judge-demo'
      preLoaderRoute: typeof JudgeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$analysisId': {
      id: '/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof AnalysesAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  JudgeDemoRoute: JudgeDemoRoute,
  NewRoute: NewRoute,
  TasksRoute: TasksRoute,
  AnalysesAnalysisIdRoute: AnalysesAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
